trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  Major: 3
  Minor: 99
  BuildConfiguration: 'Release'

name: $(Major).$(Minor).$(BuildID)

steps:
- checkout: self
  submodules: true

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '$installerPath = "$($env:USERPROFILE)\\InnoDownloader.exe";
      (New-Object Net.WebClient).DownloadFile("https://drive.google.com/uc?export=download&id=0Bzw1xBVt0mokWHlicktGUVNXeTA", $installerPath);
      cmd /c start /wait $installerPath /verysilent'
      
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.0.100-preview5-011568'
    includePreviewVersions: true
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    feedsToUse: 'select'
    versioningScheme: byBuildNumber
    arguments: '--configuration $(BuildConfiguration) /p:Version=$(Build.BuildNumber);FileVersion=$(Build.BuildNumber)'

- task: CmdLine@2
  inputs:
    script: 'iscc /Q "Setup Script.iss"'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'ServerStaging'
    ArtifactName: 'artifact'
    publishLocation: 'Container'    