# .NET Desktop

# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: self
  submodules: true

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '$installerPath = "$($env:USERPROFILE)\\InnoDownloader.exe";
      (New-Object Net.WebClient).DownloadFile("https://drive.google.com/uc?export=download&id=0Bzw1xBVt0mokWHlicktGUVNXeTA", $installerPath);
      cmd /c start /wait $installerPath /verysilent'
      
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.0.100-preview5-011568'
    includePreviewVersions: true
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    feedsToUse: 'select'
    versioningScheme: 'off'

- task: CmdLine@2
  inputs:
    script: 'iscc /Q "Setup Script.iss"'