name: CI

on: [push]

jobs:
  build:
    runs-on: windows-2019  
    steps:
    - uses: actions/checkout@master
    - name: Git Submodules Init
      uses: chris-short/github-action-git-submodules@v0.1.0
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100' # SDK Version to use.
    - run: dotnet build OutlookDesktop.sln
