name: CI

on: [push]

jobs:
  build:

    runs-on: windows-2019
    
    
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100-preview9-014004' # SDK Version to use.
    - run: dotnet build OutlookDesktop.sln
